make:
	python main01_ReadCsvFile.py
	python main02_IndexingByJanome.py
	python main03_SVM_sLB.py

lda:
	python lda_extract.py
	python lda_read_csv.py
	python lda_indexing_janome.py
	python main03_LDA_tomoto.py